# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'jimeh/tmux-themepack'

# Enable mouse scrolling
setw -g mouse on

# Windows indexed 1
set -g base-index 1
set -g pane-base-index 1

# Change prefix from 'Ctrl+B' to 'Ctrl+Space'
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# Keybinding to enter copy-mode
bind-key C-u copy-mode

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
